package itu.zazart.erpnext.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class PurchaseOrder {

    private String name;
    private Date creation;
    private Date modified;
    private String modifiedBy;
    private String owner;
    private int docstatus;
    private int idx;
    private String title;
    private String namingSeries;
    private String supplier;
    private String supplierName;
    private String orderConfirmationNo;
    private Date orderConfirmationDate;
    private Date transactionDate;
    private Date scheduleDate;
    private String company;
    private int applyTds;
    private String taxWithholdingCategory;
    private int isSubcontracted;
    private String supplierWarehouse;
    private String amendedFrom;
    private String costCenter;
    private String project;
    private String currency;
    private BigDecimal conversionRate;
    private String buyingPriceList;
    private String priceListCurrency;
    private BigDecimal plcConversionRate;
    private int ignorePricingRule;
    private String scanBarcode;
    private String setFromWarehouse;
    private String setWarehouse;
    private BigDecimal totalQty;
    private BigDecimal totalNetWeight;
    private BigDecimal baseTotal;
    private BigDecimal baseNetTotal;
    private BigDecimal total;
    private BigDecimal netTotal;
    private BigDecimal taxWithholdingNetTotal;
    private BigDecimal baseTaxWithholdingNetTotal;
    private String setReserveWarehouse;
    private String taxCategory;
    private String taxesAndCharges;
    private String shippingRule;
    private String incoterm;
    private String namedPlace;
    private BigDecimal baseTaxesAndChargesAdded;
    private BigDecimal baseTaxesAndChargesDeducted;
    private BigDecimal baseTotalTaxesAndCharges;
    private BigDecimal taxesAndChargesAdded;
    private BigDecimal taxesAndChargesDeducted;
    private BigDecimal totalTaxesAndCharges;
    private BigDecimal baseGrandTotal;
    private BigDecimal baseRoundingAdjustment;
    private String baseInWords;
    private BigDecimal baseRoundedTotal;
    private BigDecimal grandTotal;
    private BigDecimal roundingAdjustment;
    private BigDecimal roundedTotal;
    private int disableRoundedTotal;
    private String inWords;
    private BigDecimal advancePaid;
    private String applyDiscountOn;
    private BigDecimal baseDiscountAmount;
    private BigDecimal additionalDiscountPercentage;
    private BigDecimal discountAmount;
    private String otherChargesCalculation;
    private String supplierAddress;
    private String addressDisplay;
    private String contactPerson;
    private String contactDisplay;
    private String contactMobile;
    private String contactEmail;
    private String shippingAddress;
    private String shippingAddressDisplay;
    private String billingAddress;
    private String billingAddressDisplay;
    private String customer;
    private String customerName;
    private String customerContactPerson;
    private String customerContactDisplay;
    private String customerContactMobile;
    private String customerContactEmail;
    private String paymentTermsTemplate;
    private String tcName;
    private String terms;
    private String status;
    private String advancePaymentStatus;
    private BigDecimal perBilled;
    private BigDecimal perReceived;
    private String letterHead;
    private int groupSameItems;
    private String selectPrintHeading;
    private String language;
    private Date fromDate;
    private Date toDate;
    private String autoRepeat;
    private int isInternalSupplier;
    private String representsCompany;
    private String refSq;
    private String partyAccountCurrency;
    private String interCompanyOrderReference;
    private int isOldSubcontractingFlow;
    private String userTags;
    private String comments;
    private String assign;
    private String likedBy;
}
